all:
	gcc main_fcfs.c -o main_fcfs -Wall -Werror -Wextra -pedantic -O2
	cat data.txt | ./main_fcfs
	rm main_fcfs

bin:
	gcc main_fcfs.c -o main_fcfs -Wall -Werror -Wextra -pedantic -O2


clean:
	rm main_fcfs
